[auth]
secret-key = "supertopsecret"
algorithm = "HS256"
access-token-expire-minutes = 60

[mongo]
# host = "mongodb"
host = "localhost"
port = 27017
db = "dfs-drive"

[minio]
# host = "minio"
host = "localhost:9000"
username = "minio"
password = "minio123"
bucket = "data-drive"