[auth]
secret-key = "supertopsecret"
algorithm = "HS256"
access-token-expire-minutes = 60

[mongo]
host = "localhost"
port = 27017
db = "dfs-drive"

[minio]
host = "localhost:9000"
username = "minio"
password = "minio123"
