[drive]
max-preview-size = 10980920
min-bandwidth = 3533931
default-user-quota = 54818350226
default-user-permission = 1
allowed-file-extensions = [
    ".png",
    ".jpg",
    ".webp",
    ".pdf",
    ".tex",
    ".md",
]
